### PR TITLE
fix: get hostname consistently

### LINKED ISSUE #242: `nh home` on darwin should use same hostname logic as `nh darwin`
Here is what we us on `nh darwin`
https://github.com/nix-community/nh/blob/7bd0d00a3f1aab85a7e29d34b4f1f6744263e6c3/src/darwin.rs#L36-L65

`nh home` use the same logic as `nh os`
https://github.com/nix-community/nh/blob/7bd0d00a3f1aab85a7e29d34b4f1f6744263e6c3/src/home.rs#L173-L177

https://github.com/nix-community/nh/blob/7bd0d00a3f1aab85a7e29d34b4f1f6744263e6c3/src/nixos.rs#L66-L73

> I'm using the master branch (`4.0.0-beta.11`), and `nh home switch` doesn't work on darwin, since my flake exports the hostname without `.local`, but `nh` is trying to switch using `.local`.
> 
> The fix in my case would be if `nh` trimmed off the domain part of the hostname with:
> ```rust
> let hostname = hostname::get();
> let hostname.split_once('.').map(|(hostname, _)| hostname).unwrap_or(hostname);
> ```
> For now, I don't know if there's any solution here? I just can't use `nh home` on my darwin setup. 

 _Originally posted by @tqwewe in [#149](https://github.com/nix-community/nh/issues/149#issuecomment-2765995406)_

### PR DESCRIPTION
**Pull request by thecaralice**
Fixes #242

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -4,7 +4,7 @@ use std::path::{Path, PathBuf};
 use std::process::Command;
 use std::str;
 
-use color_eyre::{eyre, Result};
+use color_eyre::{eyre, eyre::bail, eyre::Context, Result};
```
Comment (ToyVo) [inline src/util.rs]: This is what I get running `fix.sh` in your branch
```suggestion
use color_eyre::{eyre, eyre::bail, Result};
```
